#!/usr/bin/env python3
"""
Script 6: generate_value_report.py
Purpose: Generates a client-facing Value Report from run artifacts.
Usage: python generate_value_report.py --run_id <id> --output_dir <dir>
"""

import argparse
import sys
import os
import json
import logging
from datetime import datetime

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def generate_markdown(run_data, domain):
    date = datetime.now().strftime("%Y-%m-%d")
    
    # Extract metrics
    start_e = run_data.get("optimization", {}).get("start_energy", 0.0)
    final_e = run_data.get("optimization", {}).get("final_energy", 0.0)
    delta = run_data.get("optimization", {}).get("energy_delta", 0.0)
    steps = run_data.get("optimization", {}).get("steps", 0)
    
    safety = run_data.get("safety", {}).get("status", "Unknown")
    power = run_data.get("safety", {}).get("power_watts", 0.0)
    
    deployment_id = run_data.get("deployment", {}).get("deployment_id", "N/A")
    
    md = f"""# Industriverse Value Report: {domain.upper()} Optimization

**Date:** {date}
**Run ID:** {run_data.get('run_id')}
**Status:** {safety.upper()}

---

## Executive Summary
We have successfully optimized the **{domain}** domain using our Energy-Based Diffusion Engine. The system identified a lower-energy equilibrium state that satisfies all thermodynamic constraints.

### Key Metrics
| Metric | Initial | Optimized | Delta |
| :--- | :--- | :--- | :--- |
| **System Energy** | {start_e:.4f} J | **{final_e:.4f} J** | **{delta:.4f} J** |
| **Stability Score** | {(1.0 - start_e):.2f} | **{(1.0 - final_e):.2f}** | +{(start_e - final_e):.2f} |
| **Power Load** | N/A | {power:.1f} W | Optimal |

---

## Technical Verification

### 1. Diffusion Optimization
- **Engine:** Industriverse IDF v1.0
- **Steps:** {steps}
- **Convergence:** {run_data.get("optimization", {}).get("converged")}
- **Entropy:** {run_data.get("optimization", {}).get("trajectory_entropy"):.4f} bits

### 2. Safety Compliance (AI Shield)
- **Status:** {safety}
- **Violations:** {run_data.get("safety", {}).get("safety_violations", [])}

### 3. Deployment
- **Capsule ID:** {domain}_v1
- **Deployment ID:** {deployment_id}
- **Runtime Monitor:** Active

---

## Recommendation
The optimized configuration has been verified and deployed to the Sovereign Gateway. No further action is required.

*Generated by Industriverse Regiment*
"""
    return md

def main():
    parser = argparse.ArgumentParser(description="Generate Value Report.")
    parser.add_argument("--run_data", type=str, required=True, help="Path to aggregated run JSON.")
    parser.add_argument("--output_dir", type=str, default="artifacts/reports", help="Output directory.")
    
    args = parser.parse_args()
    
    try:
        with open(args.run_data, "r") as f:
            data = json.load(f)
    except FileNotFoundError:
        logger.error("Run data file not found.")
        sys.exit(1)
        
    domain = data.get("domain", "unknown")
    run_id = data.get("run_id", "unknown")
    
    logger.info(f"Generating report for Run {run_id} ({domain})...")
    
    report_content = generate_markdown(data, domain)
    
    os.makedirs(args.output_dir, exist_ok=True)
    out_path = os.path.join(args.output_dir, f"ValueReport_{domain}_{run_id}.md")
    
    with open(out_path, "w") as f:
        f.write(report_content)
        
    logger.info(f"Report generated: {out_path}")
    print(out_path) # Print path for pipe usage

if __name__ == "__main__":
    main()
