import logging
from typing import Dict, Any

logger = logging.getLogger("ValueRealization")

class ValueRealizationEngine:
    """
    Quantifies the value generated by the Sovereign Code Foundry.
    Converts thermodynamic savings (Joules) and operational uptime into:
    1. Negentropy Credits (Internal Currency)
    2. Economic Value (USD Estimate)
    3. Scalar Reward (For RL Training)
    """
    def __init__(self, energy_price_per_kwh=0.15, downtime_cost_per_hour=1000.0):
        self.energy_price_per_joule = energy_price_per_kwh / (3.6 * 10**6) # $/Joule
        self.downtime_cost_per_sec = downtime_cost_per_hour / 3600.0
        
    def compute_value(self, deployment_result: Dict[str, Any]) -> Dict[str, float]:
        """
        Computes the realized value of a deployment.
        """
        # 1. Extract Metrics
        joules_saved = deployment_result.get("energy_trace_summary", {}).get("joules_saved", 0.0)
        downtime_avoided_sec = deployment_result.get("operational_impact", {}).get("downtime_avoided_sec", 0.0)
        
        # 2. Calculate Economic Value
        energy_savings_usd = joules_saved * self.energy_price_per_joule
        downtime_savings_usd = downtime_avoided_sec * self.downtime_cost_per_sec
        total_usd = energy_savings_usd + downtime_savings_usd
        
        # 3. Calculate Negentropy Credits (1 Credit = 1 MJ Saved or Equivalent)
        negentropy_credits = (joules_saved / 10**6) + (downtime_avoided_sec * 0.1)
        
        # 4. Calculate Scalar Reward (Normalized 0-1 for RL, but can go higher for super-performance)
        # Baseline reward is 0.1 for successful deploy
        reward = 0.1
        if total_usd > 0:
            reward += min(total_usd / 10.0, 1.0) # Cap linear reward contribution
        if negentropy_credits > 0:
            reward += min(negentropy_credits, 1.0)
            
        logger.info(f"💰 Value Realized: ${total_usd:.4f} | ⚡ {negentropy_credits:.4f} Credits | 🎁 Reward: {reward:.4f}")
        
        return {
            "usd_value": total_usd,
            "negentropy_credits": negentropy_credits,
            "rl_reward": reward
        }
