# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: csi_schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'csi_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63si_schema.proto\x12\x08\x64ome.csi\"\xc1\x01\n\x08\x43SIFrame\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x11\n\tamplitude\x18\x03 \x03(\x02\x12\r\n\x05phase\x18\x04 \x03(\x02\x12\x17\n\x0fnum_subcarriers\x18\x05 \x01(\r\x12\x14\n\x0cnum_antennas\x18\x06 \x01(\r\x12\x15\n\rsampling_rate\x18\x07 \x01(\x02\x12\x15\n\rhardware_type\x18\x08 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\t \x03(\x02\"w\n\x0cSensingEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x18\n\x10motion_signature\x18\x04 \x03(\x02\x12\x12\n\nproof_hash\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csi_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSIFRAME']._serialized_start=31
  _globals['_CSIFRAME']._serialized_end=224
  _globals['_SENSINGEVENT']._serialized_start=226
  _globals['_SENSINGEVENT']._serialized_end=345
# @@protoc_insertion_point(module_scope)
