#!/usr/bin/env python3
import os, json, uuid
import click
import yaml

TEMPLATE_MANIFEST = {
  "dac_id": "",
  "version": "1.0.0",
  "hardware_target": "jetson|esp32",
  "inputs": ["CSI_stream"],
  "outputs": ["event_presence", "signed_proof"],
  "energy_prior": "",
  "tnn_solver": ""
}

@click.group()
def cli():
    pass

@cli.command()
@click.argument('dac_name')
@click.option('--prior','-p', default='fusion_v1', help='energy prior to bind')
@click.option('--tnn','-t', default='fusion_ham', help='TNN solver to include')
@click.option('--out', default='src/capsules/sovereign', help='Output directory')
def new(dac_name, prior, tnn, out):
    target_dir = os.path.join(out, dac_name)
    os.makedirs(target_dir, exist_ok=True)
    
    manifest = TEMPLATE_MANIFEST.copy()
    manifest['dac_id'] = dac_name
    manifest['energy_prior'] = prior
    manifest['tnn_solver'] = tnn
    
    with open(os.path.join(target_dir,'manifest.yaml'),'w') as f:
        yaml.safe_dump(manifest, f)
        
    with open(os.path.join(target_dir,'README.md'),'w') as f:
        f.write(f"# {dac_name}\nGenerated by DAC Builder\n")
        
    # Generate simple schema
    schema = {"id": dac_name, "title": dac_name, "widgets": []}
    with open(os.path.join(target_dir, "dac_schema.json"), "w") as f:
        json.dump(schema, f, indent=2)
        
    print(f"Created DAC {dac_name} at {target_dir}")

if __name__ == '__main__':
    cli()
