import os
import sys
import time
import json

# Add project root to path
sys.path.append(os.path.join(os.path.dirname(__file__), "../.."))
from src.datahub.value_vault import ValueVault

def generate_brief():
    vault = ValueVault()
    secrets = vault.get_latest_secrets(limit=3)
    
    if not secrets:
        print("No high-value secrets found to publish.")
        return

    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    brief_content = f"""# EMPEIRIA INSIGHTS: RESEARCH BRIEF
**Date**: {timestamp}
**Classification**: PUBLIC DISCLOSURE
**Source**: Empeiria Haus Autonomous Research Engine

---

## 🚀 Executive Summary
The Empeiria Haus system has detected significant thermodynamic breakthroughs in the last cycle.
These insights represent "Monopoly Value" generated by the Industriverse-Thermodynasty-Empeiria Trinity.

---

## 💎 High-Value Discoveries

"""

    for secret in secrets:
        insight = secret.get("insight", {})
        thermo = insight.get("thermodynamics", {})
        brief_content += f"""### 🔹 Secret ID: {secret.get('id')}
*   **Negentropy Score**: {thermo.get('negentropy_score')} J/K
*   **Thermal Efficiency**: {thermo.get('thermal_efficiency')}
*   **Innovation Potential**: {thermo.get('innovation_potential')}
*   **Observation**: System achieved high order with minimal energy input.

"""

    brief_content += """
---
**Impact Statement**:
These metrics demonstrate that the Industriverse OS is actively reversing entropy in industrial systems,
creating net-new value that exceeds the energy cost of computation.

*Generated by Empeiria Haus Auto-Publisher*
"""

    # Publish
    output_dir = "public/briefs"
    os.makedirs(output_dir, exist_ok=True)
    filename = f"brief_{int(time.time())}.md"
    path = os.path.join(output_dir, filename)
    
    with open(path, 'w') as f:
        f.write(brief_content)
    
    print(f"✅ Published Research Brief: {path}")
    print(brief_content)

if __name__ == "__main__":
    generate_brief()
